$(warning ************************************************************)
$(warning The full_npm801 target is no longer supported)
$(warning Please use aosp_npm801 instead)
$(warning $(space))
$(warning When switching from full_npm801 to aosp_npm801 it is essential)
$(warning to follow the upgrade procedure in .../device/ingenic/npm801/README)
$(warning Switching to aosp_npm801 will require a full reinstall and all)
$(warning data on the tablet will be erased!)
$(warning ************************************************************)
$(error stop)
