#!/bin/bash
#
# Copyright (c) 2013,2014,2016 Imagination Technologies
# Original-Author: Chris Larsen <chris.larsen@imgtec.com>
#
# Writes Android filesystems to the sd card for Ingenic tablet (NPM801).
# Derived from the CI20 version of the file with the same name.
#
# Usage:
#   ./mksdcard-ext4 /dev/sdX
#

set -e
tmpDir=`mktemp -d`

cleanup()
{
  echo "Cleaning up..."
  rm -rf ${tmpDir}
  [ "${finished}" = "true" ] && sudo eject ${device} && echo "Cleanup completed; it is safe to remove your card"
  trap - EXIT INT TERM
}
trap cleanup EXIT INT TERM

die()
{
  echo "$@" >&2
  exit 1
}

sfdisk_npm801()
{
  sfdisk_tool=`which sfdisk`
  blockdev_tool=`which blockdev`
  partprobe_tool=`which partprobe`

  [ -f "$sfdisk_tool" ] || die "No sfdisk in \$PATH"
  [ -f "$blockdev_tool" ] || die "No blockdev in \$PATH"
  [ -f "$partprobe_tool" ] || die "No partprobe in \$PATH"
  [ -b "$1" ] || die "Device '$1' not found"

  sfdisk_version=`$sfdisk_tool --version | sed 's,.*2\.\([0-9]*\)\.[0-9]*,\1,'`

  unset sfdisk_is_ancient
  test $sfdisk_version -lt 26 && sfdisk_is_ancient=1

  sfdisk_dev="$1"
  shift

  sfdisk_parts=`echo $* | tr ' ' '\n'`

  set +e
  if [ $sfdisk_is_ancient ]; then
      echo "$sfdisk_parts" | tr -d M | sudo $sfdisk_tool -L -uM "$sfdisk_dev"
  else
      echo "$sfdisk_parts" | sudo $sfdisk_tool "$sfdisk_dev"
  fi
  set -e

  sudo $blockdev_tool --rereadpt $sfdisk_dev
  sudo $partprobe_tool $sfdisk_dev
  sleep 2
}

# check device
device="$1"
[ -e "${device}" ] || die "Device '${device}' not found"
grep ${device} /etc/mtab >/dev/null && \
  die "Device '${device}' contains mounted partitions"

# check for Android images
systemImg=${SYSTEMIMG:-${OUT}/system.img}
[ -e "${systemImg}" ] || die "Android system image '${systemImg}' not found"

# check for tools
which bc >/dev/null || die "No bc in \$PATH"

# FIXME: sfdisk often fails to reread the partition information

# If you change the size of partition two here be sure to change
# the size of BOARD_SYSTEMIMAGE_PARTITION_SIZE in ../BoardConfig.mk
# for the case when WITH_SDCARD is true.
if [ "$WITH_GMS" == "true" ]; then
  sfdisk_npm801 ${device} 2M,30M 32M,1750M 1782M,256M 2038M,2048M
else
  sfdisk_npm801 ${device} 2M,30M 32M,1000M 1032M,256M 1288M,2048M
fi

partitions=("Boot" "System" "Cache" "Data")

for((i=4; i>0; i--));
do

  if [ -e "$device$i" ]; then
    part=${i}
  elif [ -e "${device}p$" ]; then
    part="p${i}"
  fi

  if [ $i -eq 2 ]; then
    partSystem=${part}
  fi

  # create ext4 data partition
  sudo mkfs.ext4 -L "${partitions[$i-1]}" ${device}${part}
done

echo
echo "Please wait, writing system.img"

sudo dd if=${systemImg} of=${device}${partSystem}

echo

finished=true
echo
echo "Finished, wait for clean up before removing your card!"
